### ISSUE TITLE
「舉」字會變成「擧」字

### ISSUE THREAD

**Issue by weimming** [ButTaiwan/genseki-font#3]
「舉」字會變成「擧」字，下面變成「手」字，在此告知，辛苦了。

**Comment by ButTaiwan** [comment]
Ver 1.300 時故意整合一些異體字為相同字形，經評估後「舉」字已在 Ver 1.500 重新分開。
![image](https://user-images.githubusercontent.com/5418570/79038903-bdddba00-7c0f-11ea-8131-2eaf71171698.png)
