### ISSUE TITLE
建議要改 "人" 部

### ISSUE THREAD

**Issue by CoolMarvel43** [ButTaiwan/genseki-font#4]
![Annotation 2020-05-09 171301](https://user-images.githubusercontent.com/10541683/81469753-700d9f00-9219-11ea-9995-d2df60c4ecf8.png)
像游黑體 "人" 部的上面，但不要完全複製。

**Comment by ButTaiwan** [comment]
這是會影響到文字佈局的改變，應該是做不到。

（為了要爭取那一點點襯線空間，要不是捺筆下移或變細，就是整體變高，但都會大幅影響文字美觀。）
