### ISSUE TITLE
關于“尚”部件的問題

### ISSUE THREAD

**Issue by garfieldLSY** [ButTaiwan/genseki-font#7]
這個問題，許多基于思源字體的傳承字形字體都存在，就連舊刊宋、老報宋、不明體也存在。
“尚”的傳承自形應該是“尙”，但是在這個字體，以及幾乎所有的思源字體裏，像“躺”、“淌”這兩個常用字右邊的“尚”仍然是新字形。
（注：“䝼”這個字右邊也是，所有思源字體傳承字形字體都没有把右邊的“青”改成“靑”）

**Comment by ButTaiwan** [comment]
在多數的鉛字裡，尚可能才是多數派。（本專案追求的是70年代常見鉛字風格）

![image](https://user-images.githubusercontent.com/5418570/158201612-ee7c3271-fa18-47c5-b7b6-0d1e59e8b69c.png)
(國語日報字典)

康熙字典的尚字本身是尙，但作為部件時也經常都是尚。
![image](https://user-images.githubusercontent.com/5418570/158201668-19c1a02e-6fc4-4e13-b615-f7627e023b9a.png)

於是在任何地區標準裡，都是尚。
![image](https://user-images.githubusercontent.com/5418570/158202461-e8ab33b8-cc9e-427f-bb37-cf5cd843cedb.png)

> “䝼”這個字右邊也是

如同首頁說明。本專案並沒有造新的字符，所有字符都是來自思源宋體本身。所以KR版本未收錄的罕用字或簡化字，仍然會是TW、CN風格。

**Comment by garfieldLSY** [comment]
原來如此……



---- 回复的原邮件 ----
| 发件人 | But ***@***.***> |
| 日期 | 2022年03月14日 23:14 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [ButTaiwan/genseki-font] 關于“尚”部件的問題 (Issue #7) |

在多數的鉛字裡，尚可能才是多數派。（本專案追求的是70年代常見鉛字風格）


(國語日報字典)

康熙字典的尚字本身是尙，但作為部件時也經常都是尚。


於是在任何地區標準裡，都是尚。


“䝼”這個字右邊也是

如同首頁說明。本專案並沒有造新的字符，所有字符都是來自思源宋體本身。所以KR版本未收錄的罕用字或簡化字，仍然會是TW、CN風格。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by garfieldLSY** [comment]
原來如此……
不過我記得在老臺標裏，“尚”作爲左右結構構件的時候還是“尙”（參考古越軒粗明體、王漢宗超明體、華康明體和老臺標的華文黑體），不過你也説了，這源雲、源流、源樣衹會使用思源宋體以内的字，所以……不妨把“趟”和“倘”的字形改成日本/中國的？



---- 回复的原邮件 ----
发件人 But ***@***.***>日期 2022年03月14日 23:14 收件人 ***@***.***>抄送至 ***@***.******@***.***>主题 Re: [ButTaiwan/genseki-font] 關于“尚”部件的問題 (Issue #7)
在多數的鉛字裡，尚可能才是多數派。（本專案追求的是70年代常見鉛字風格）

(國語日報字典)
康熙字典的尚字本身是尙，但作為部件時也經常都是尚。

於是在任何地區標準裡，都是尚。

“䝼”這個字右邊也是
如同首頁說明。本專案並沒有造新的字符，所有字符都是來自思源宋體本身。所以KR版本未收錄的罕用字或簡化字，仍然會是TW、CN風格。
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
