### ISSUE TITLE
 README.md の誤字？

### ISSUE THREAD

**Issue by Hackgets** [ButTaiwan/genseki-font#8]
細かいことで恐縮なんですが、 README.mdに「源様ゴシック」とあるのは「源石ゴシック」の誤りでしょうか？
![Screenshot 2022-08-13 at 06-32-21 ButTaiwan_genseki-font A free font family derived from Source Han Sans](https://user-images.githubusercontent.com/102782728/184447802-cf623d28-a4a4-4ce0-87ef-c7997f5b0bb3.png)

**Comment by ButTaiwan** [comment]
そうですね。誤字です。
「源様ゴシック（ https://github.com/ButTaiwan/genyog-font ）」のコピペがばれましたかｗ。
